### ISSUE TITLE
[Bug]: Headers get squished

### ISSUE THREAD

**Issue by ReaderGuy42** [chrisgrieser/shimmering-focus#140]
### Bug Description

Not sure how long this has been (I think only starting today) but headers seem to be getting squished (see screenshot).

This does not occur in the default theme. But it does occur with the default header font (the one that's the default in Style Settings; in the screen shot I use "GloucesterW01-Bold"). I also installed the theme and Style Settings in the Help vault, and the same thing happens.

I think this only happens in Live Preview. It does NOT happen in Reading or Source mode.

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/71895400/163186825-d5679968-290f-4723-aec3-08c81f12f8f5.png)

### To Reproduce

1. Use theme
2. have header
3. see header with multiple lines is squished.

### Obsidian Version

0.14.5

### Installer Version

0.13.30

### Which editor are you using?

- [ ] New Editor
- [ ] Legacy Editor

### In which mode(s) does the problem occur? (if applicable)

- [ ] Source (Edit)
- [ ] Reading (Preview)
- [X] Live Preview

### Which operating system?

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] iOS
- [ ] Android

### Plugin-Specific Problems

- [X] I took note of the [specific instructions regarding those plugins](https://chrisgrieser.github.io/shimmering-focus/plugin-specific-features/#instructions-for-specific-plugins).

### Checklist

- [X] I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
- [X] I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
- [X] In case I am missing an UI element, I have checked that it cannot be re-enabled with the [Style Settings plugin](https://github.com/mgmeyers/obsidian-style-settings).
- [X] If the bug occured after updating the theme, I read the last couple of entries in the [changelog](https://github.com/chrisgrieser/shimmering-focus/blob/main/docs/Changelog.md#changelog) to make sure the bug is not an intentional change. (In that case, there will most likely be a style setting to turn it off again.)

**Comment by chrisgrieser** [comment]
ah thanks, didn't notice since I rarely have long headings. Fixed with latest update

**Comment by ReaderGuy42** [comment]
Thanks :)

**Comment by ReaderGuy42** [comment]
Has that latest update gone out yet? Because the issue still seems to occur.

**Comment by chrisgrieser** [comment]
> Has that latest update gone out yet? Because the issue still seems to occur.

yeah, should be? Maybe GitHub has some hickups, try again in a few minutes?

![image](https://user-images.githubusercontent.com/73286100/163205009-69923cd3-8bbd-4460-b35b-cda0bb48ea87.png)

**Comment by chrisgrieser** [comment]
working now?

**Comment by ReaderGuy42** [comment]
Hm, no, it's still happening.

**Comment by chrisgrieser** [comment]
strange, I tried something else. try again?

**Comment by ReaderGuy42** [comment]
Yes, now it's gone, thanks!
